# This file is part of the Omicron2D RoboCup 2D Soccer Simulation team.
# General config file. Loaded by the Omicron2D client to run basic setup

# Networking config
teamName: Omicron2D
serverHost: localhost
playerPort: 6000
trainerPort: 6001
coachPort: 6002
timeout: 10000 # milliseconds

# GUI config
showDebugDisplay: false

# Formations
initialFormation: formations/starting433.yml

# Agent AI config
# There's currently no good reason to listen to the opposition, but in future it would be interesting to
# intercept agent2d messages and attempt to decode them
listenToOpposition: false
# Move to Point behaviour
# P-D controller constants
moveKp: 25.0
moveKd: 0.5
# Distance at which to consider the MoveToPoint behaviour point as being "reached"
movePointReachedThresh: 1.0
# Turn Body To behaviour
# P-D controller constants, in degrees (will be converted to radians)
turnBodyKp: 6.0
turnBodyKd: 2.0
# Number of degrees tolerance where we consider the body angle as being reached
turnBodyToleranceDeg: 4.0

# Field definitions
# Source: https://github.com/rcsoccersim/rcssserver/blob/master/src/serverparam.cpp#L130
fieldLength: 105
fieldWidth: 68