# This file is part of the Omicron2D RoboCup 2D Soccer Simulation team.
# Config file for agent behaviour (GOAP)

- name: WorldScanNormal
  cost: 3
  preConditions:
    - LowInfo: true
      MustQuickScan: false
  postConditions:
    - LowInfo: false
  # this part declares how to actually execute the behaviour
  movement:
    - class: WorldScanMovementBehaviour # instantiate this class
      isFastScan: false # pass this argument to the constructor
      numScans: 3
  orientation:
    - class: WorldScanOrientationBehaviour
      speed: normal
  communication:
    - class: SmartCommsBehaviour # be sensible, send default info
    # no arg constructor