# General config file. Loaded by the Omicron2D client to run basic setup

# Networking config
teamName: Omicron2D
serverHost: localhost
playerPort: 6000
trainerPort: 6001
coachPort: 6002
timeout: 10000 # milliseconds

# ICP config
icpMaxIters: 255
icpTolerance: 0.001