# General config file. Loaded by the Omicron2D client to run basic setup

# Team specific stuff
teamName: Omicron2D

# Networking
serverHost: localhost
playerPort: 6000
trainerPort: 6001
coachPort: 6002
timeout: 10000