intext = """UNKNOWN
BEFORE_KICK_OFF
TIME_OVER
PLAY_ON
KICK_OFF_L
KICK_OFF_R
KICK_IN_L
KICK_IN_R
FREE_KICK_L
FREE_KICK_R
CORNER_KICK_L
CORNER_KICK_R
GOAL_KICK_L
GOAL_KICK_R
GOAL_L
GOAL_R
DROP_BALL
OFFSIDE_L
OFFSIDE_R
PENALTY_KICK_L
PENALTY_KICK_R
FIRST_HALF_OVER
PAUSE
HUMAN_JUDGE
FOUL_CHARGE_L
FOUL_CHARGE_R
FOUL_PUSH_L
FOUL_PUSH_R
FOUL_MULTIPLE_ATTACK_L
FOUL_MULTIPLE_ATTACK_R
FOUL_BALLOUT_L
FOUL_BALLOUT_R
BACK_PASS_L
BACK_PASS_R
FREE_KICK_FAULT_L
FREE_KICK_FAULT_R
CATCH_FAULT_L
CATCH_FAULT_R
INDIRECT_FREE_KICK_L
INDIRECT_FREE_KICK_R
PENALTY_SETUP_L
PENALTY_SETUP_R
PENALTY_READY_L
PENALTY_READY_R
PENALTY_TAKEN_L
PENALTY_TAKEN_R
PENALTY_MISS_L
PENALTY_MISS_R
PENALTY_SCORE_L
PENALTY_SCORE_R
ILLEGAL_DEFENSE_L
ILLEGAL_DEFENSE_R"""

if __name__ == "__main__":
    lines = intext.split("\n")
    for line in lines:
        print(f"| '{line}'")